services:
  snapclient:
    build: .
    network_mode: host
    restart: unless-stopped
    environment:
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native:ro
