dummy: ENC[AES256_GCM,data:aWFvog==,iv:dwd9iSVBTNBdpry6+PFWSynh5OPRkj/9oAoBRwLmdqk=,tag:wLeL+olLdyFgH8OHiMwSuQ==,type:str]
sops:
    age:
        - recipient: age1wvuj20gp2e775mmum6wc2qp8ky4mk7vx0tc8yn89vplq69ryfqlsjffpfq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiV1BISzhGSnNQWS9jV2gy
            NTd2VFJ2TnJBV0VlS0p6QUMzL3FyZld2WW1zCjJ1Y1J3ZkFqMVkyK0tJNzdQaTRQ
            a3lsWFdRcFdUWUR4bmlxNjA2MDQyTXMKLS0tIDZtUUkyU3ZGTXB1bVFEV2JtbU8w
            SE9iRG5YQ3p3dXU4RXh0YVZaaTczYzQKFQgUoyArjut2Gu1t9JNtIULU51VGTkdr
            kEutsrbl50/zTag35QAHJt2T3dJhfEqPUNldkD+LplaCeGiWaftJtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T12:28:21Z"
    mac: ENC[AES256_GCM,data:BBU2l4rJMr2TWo3TLtvOtx4taXzGaxKyHOJtNCYkpXmtOM07bs4GBxfg8jl67Yay29lhgiboQdypPJP0+pTET+Eu5+deTezZvvpfwqzbTJ9epNs+f3cSo3dhIJxN0WRYO1wub8Zm2lum7ws0nf1tbbuFlYaruDxQrRQ1719LePY=,iv:qheSUZvtXhagdk9INMALjTvzYnyDSmYF1WJxvpCxYJY=,tag:6+vbn5K8ibi/ivD/Ak+ylw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
