spotifyUser: ENC[AES256_GCM,data:M892UHw89gKlcZjQrxkKIk62Nw==,iv:H3eguR+gfUsmDS17PyUM3gmDRoDM9eKhSYL0gqIPlts=,tag:5raVWUksvqv9M/CvWHMc3g==,type:str]
spotifyPass: ENC[AES256_GCM,data:el9MUjdYB9yqVVwXedEm,iv:UCQW8bgeiWJFJG9PMQUMMuc4/AqfOVm7bNFr8hK/SFA=,tag:TXEvYUfrCbuzmewm01h63Q==,type:str]
sops:
    age:
        - recipient: age1wvuj20gp2e775mmum6wc2qp8ky4mk7vx0tc8yn89vplq69ryfqlsjffpfq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiV1BISzhGSnNQWS9jV2gy
            NTd2VFJ2TnJBV0VlS0p6QUMzL3FyZld2WW1zCjJ1Y1J3ZkFqMVkyK0tJNzdQaTRQ
            a3lsWFdRcFdUWUR4bmlxNjA2MDQyTXMKLS0tIDZtUUkyU3ZGTXB1bVFEV2JtbU8w
            SE9iRG5YQ3p3dXU4RXh0YVZaaTczYzQKFQgUoyArjut2Gu1t9JNtIULU51VGTkdr
            kEutsrbl50/zTag35QAHJt2T3dJhfEqPUNldkD+LplaCeGiWaftJtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T21:40:27Z"
    mac: ENC[AES256_GCM,data:0ejIcHJenQGpi+evFS2DAJ3zoABPec29I6oU15kNDaQrsGgeQY7oAWW74TqeQzCBnbHV69BQonG5mJB+ITaiHnUHzDQa9LhWc5qrAScFpDMg/dpxTlG7dwduX3Hjb4CkeEV2+DUOpzeK4p0XzxKPXl8M3BljK5BAK/8avm5rThg=,iv:36487FZdExL2zejqEbP0L0Hl8rNf7tsaLWGLopY7wAE=,tag:wBMtAP7E1gzC0z5MIWUIcA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
