#!/bin/bash

LookingGlassCMD="looking-glass-client audio:micDefault=allow spice:audio=yes"

$Dotfiles/scripts/app-workspace "special:windows" "kitty --class kitty-windows bash -ic 'virsh start Windows11; sleep 1 && $LookingGlassCMD; zsh'" "$1"
