#!/bin/bash

rm "$HOME/.cache/rclone/bisync/GoogleDrive_..home_$(whoami)_GoogleDrive.lck"


sync_drive() {
    output=$(rclone bisync -v GoogleDrive:/ ~/GoogleDrive 2>&1)
    echo "$output"
    echo "$output" >> "$HOME/dotfiles/.logs/GoogleDriveSync.log"

    if echo "$output" | grep -qE "ERROR|Failed"; then
    	if echo "$output" | grep -qE "Reason"; then
        	notify-send -c error "Google Drive Sync" "$(echo "$output" | grep -E "Reason")"
    	else
        	notify-send -c error "Google Drive Sync" "$(echo "$output" | grep -E "ERROR|Failed")"
    	fi
    	sleep 720
    fi
}

while :
do
    sync_drive
    sleep 60
done
