#!/bin/bash

LOCK_FILE="$HOME/.cache/rclone/bisync/GoogleDrive_..home_yabai_GoogleDrive.lck"

rm "$LOCK_FILE"


sync_drive() {
    output=$(rclone bisync -v GoogleDrive:/ ~/GoogleDrive 2>&1)
    echo "$output"
    echo "$output" >> "$HOME/.config/hypr/.logs/GoogleDriveSync.log"

    if echo "$output" | grep -qE "ERROR|Failed"; then
    	if echo "$output" | grep -qE "Reason"; then
        	notify-send -c error "Google Drive Sync" "$(echo "$output" | grep -E "Reason")"
    	else
        	notify-send -c error "Google Drive Sync" "$(echo "$output" | grep -E "ERROR|Failed")"
    	fi
    	sleep 360
    fi
}

shutdown_process() {
    echo "[$(date +"%Y-%m-%d %H:%M:%S")][GoogleDriveSync] Initiating graceful shutdown..."
    while [ -f "$LOCK_FILE" ]; do
    	echo "[$(date +"%Y-%m-%d %H:%M:%S")][GoogleDriveSync] Waiting for synchronization to complete..."
        sleep 1
    done
    echo "[$(date +"%Y-%m-%d %H:%M:%S")][GoogleDriveSync] Google Drive Sync gracefully stopped"
    exit 0
}

trap "shutdown_process" EXIT

while :
do
    sync_drive
    sleep 60
done
