#!/bin/bash

CONFIG="$(realpath "$HOME/dotfiles/mako/config")"

start() {
    mako --config ${CONFIG} &
    ProcessId=$!
}

stop() {
    if [[ -n "$ProcessId" ]]; then
        kill "$ProcessId"
    fi
}


start
while true; do
    inotifywait -e modify "$CONFIG"
    stop
    start
done
