#!/usr/bin/env bun

const http = require("node:http");
const { exec } = require("node:child_process");

const PORT = 8523;

const routes = {
	"/health": `echo "Im fine, thanks"`,
	"/player/status": "playerctl status",
	"/player/play-pause": "playerctl play-pause",
	"/player/stop": "playerctl stop",
	"/player/prev": "playerctl previous",
	"/player/next": "playerctl next",
	"/player/forw": "playerctl position 5+",
	"/player/back": "playerctl position 5-",
	"/volume/inc": "$XDG_DATA_HOME/bin/volume --inc",
	"/volume/dec": "$XDG_DATA_HOME/bin/volume --dec",
};

const server = http.createServer((req, res) => {
	const url = req.url.replaceAll("//", "/");
	const method = req.method?.toUpperCase();

	if (method === "POST" && routes[url]) {
		exec(routes[url], (error, stdout, stderr) => {
			let result = "";
			if (error) {
				result += `=> Error: ${error.message}`;
				res.writeHead(500, { "Content-Type": "text/plain" });
				return res.end(error.message);
			}
			if (stderr) {
				result += `=> Stderr: ${stderr}`;
				res.writeHead(500, { "Content-Type": "text/plain" });
				return res.end(stderr);
			}
			result += stdout.trim() ? `=> Stdout: ${stdout}` : "";
			res.writeHead(200, { "Content-Type": "text/plain" });
			res.end(stdout);

			console.log(`[${method}][${url}] ${routes[url]} ${result}`);
		});
	} else {
		res.writeHead(404, { "Content-Type": "text/plain" });
		res.end(`Cannot ${method} ${url}`);

		console.log(`[${method}][${url}] Unknown route`);
	}
});

server.listen(PORT, () => {
	console.log(`Listening on http://0.0.0.0:${PORT}`);
	console.log();
	for (const key of Object.keys(routes)) {
		console.log(`[POST] ${key} => ${routes[key]}`);
	}
	console.log();
	console.log("--------------------------------------------");
});
