#!/usr/bin/env sh

options="Shutdown\nReboot\nSuspend"

choice=$(echo -e "$options" | fzf --ansi --highlight-line --margin=0%)

case $choice in
    "Shutdown")
        systemctl poweroff
    ;;
    "Reboot")
        systemctl reboot
    ;;
    "Suspend")
        systemctl suspend
    ;;
    *)
        exit
    ;;
esac
