#!/usr/bin/env sh

shotnow() {
	grim - | wl-copy
}

shotwin() {
	w_pos="$(hyprctl activewindow -j | jq -r '.at | join(",")')"
	w_size="$(hyprctl activewindow -j | jq -r '.size | join("x")')"
	grim -g "$w_pos $w_size" - | wl-copy
}

shotarea() {
	grim -g "$(slurp -b 1B1F28CC -w 0)" - | wl-copy
}

shotscreen() {
    grim -o "$(hyprctl -j activeworkspace | jq -r '.monitor')" - | wl-copy
}


if [[ "$1" == "--now" ]]; then
	shotnow
elif [[ "$1" == "--win" ]]; then
	shotwin
elif [[ "$1" == "--area" ]]; then
	shotarea
elif [[ "$1" == "--screen" ]]; then
	shotscreen
else
    echo -e "Available Options : --now --win --area --screen"
fi
