#!/usr/bin/env sh

shot-win() {
	w_pos="$(hyprctl activewindow -j | jq -r '.at | join(",")')"
	w_size="$(hyprctl activewindow -j | jq -r '.size | join("x")')"
	grim -g "$w_pos $w_size" - | wl-copy
}

shot-area() {
	grim -g "$(slurp -b 1B1F28CC -w 0)" - | wl-copy
}

shot-and-ocr-area() {
	grim -g "$(slurp -b 1B1F28CC -w 0)" - | tesseract stdin stdout -l eng+ukr+rus 2>/dev/null | wl-copy
}

shot-screen() {
    grim -o "$(hyprctl -j activeworkspace | jq -r '.monitor')" - | wl-copy
}


if [[ "$1" == "--win" ]]; then
	shot-win
elif [[ "$1" == "--area" ]]; then
	shot-area
elif [[ "$1" == "--screen" ]]; then
	shot-screen
elif [[ "$1" == "--ocr-area" ]]; then
	shot-and-ocr-area
else
    echo -e "Available Options : --win --area --screen --ocr-area"
fi
