#!/usr/bin/zsh

remove-desktop-entries() {
    sudo bash -c "rm ~/.local/share/applications/userapp*.desktop 2>/dev/null"
    
    sudo bash -c "rm /usr/share/applications/*openjdk.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/electron*.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/blueman-adapters.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/blueman-manager.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/cmake-gui.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/code-url-handler.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/code.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/kitty.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/qemu.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/qv4l2.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/assistant.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/designer.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/linguist.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/qdbusviewer.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/qvidcap.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/steam.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/thunar-bulk-rename.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/thunar-settings.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/thunar-volman-settings.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/vim.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/waydroid.app.install.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/waydroid.market.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/org.pulseaudio.pavucontrol.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/com.cloudflare.WarpTaskbar.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/thunar.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/xfce4-about.desktop 2>/dev/null"
    sudo bash -c "rm /usr/share/applications/lstopo.desktop 2>/dev/null"
    
    sudo update-desktop-database
}

pc() {
    case $1 in
        "i" | "install")
            sudo pikaur -S --nodiff --noedit "${@:2}" && remove-desktop-entries; $Dotfiles/scripts/pacdump
        ;;
        "r" | "remove")
            sudo pikaur -Rns "${@:2}" && remove-desktop-entries; $Dotfiles/scripts/pacdump
        ;;
        "u" | "update")
            sudo pikaur -Syu --nodiff --noedit && remove-desktop-entries; $Dotfiles/scripts/pacdump && echo && zinit self-update && zinit update --all
        ;;
        "d" | "downgrade")
            sudo downgrade "${@:2}" && remove-desktop-entries; $Dotfiles/scripts/pacdump
        ;;
        "s" | "search")
            pikaur -Ss "${@:2}"
        ;;
        "ls" | "list")
            pikaur -Q | grep "$(printf '|%s' "${@:2}" | cut -c 2-)"
        ;;
        "info")
            pikaur -Qi "${@:2}"
        ;;
        "clear")
            pikaur -Scc
        ;;
        *)
            pikaur "$@"
        ;;
    esac
}

toggle-sudo() {
    if [[ $BUFFER == sudo\ * ]]; then
        BUFFER="${BUFFER#sudo }"
    else
        BUFFER="sudo $BUFFER"
    fi
    zle end-of-line
}

get-terminal-name() {
    ps -o comm= -p "$(($(ps -o ppid= -p "$(($(ps -o sid= -p "$$")))")))"
}

code-reuse-or-new() {
    if [[ "$(get-terminal-name)" == "code" ]]; then
        /usr/bin/code --enable-features=UseOzonePlatform --ozone-platform=wayland --reuse-window "$@"
    else
        /usr/bin/code --enable-features=UseOzonePlatform --ozone-platform=wayland --new-window "$@"
    fi
}

lastcd() {
    cd "$@" && lsd --literal --icon always --color always --group-dirs first
    echo "$(pwd)" > $HOME/.cache/lastcd
}
