#!/usr/bin/zsh

export Dotfiles="$HOME/.config/dotfiles"

export VISUAL="nano"
export EDITOR="nano"

export NETIFACE="enp42s0"
export KEYBOARD="juchen-usb-keyboard"
export Projector="HDMI-A-1"
export MonitorLeft="HDMI-A-2"
export MonitorCenter="DP-4"

export ZSH_PLUGINS="/usr/share/zsh/plugins"
export ZINIT_HOME="$HOME/.local/share/zinit"
export PNPM_HOME="$HOME/.local/share/pnpm"
export NODE_PATH="/usr/lib/node_modules"


autoload -U "$Dotfiles/terminal/zsh/functions"
autoload -U select-word-style
autoload -U compinit

source "$ZINIT_HOME/zinit.zsh"


if [[ "$(tty)" == "/dev/tty1" ]]; then
    if ! pgrep -x "Hyprland" > /dev/null; then
        clear && Hyprland > /dev/null 2>&1
    fi
fi

if [ ! -d "$ZINIT_HOME" ]; then
    mkdir -p "$(dirname $ZINIT_HOME)"
    git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

if [ ! -s "${ZSH_COMPDUMP}" ]; then
    compinit -C
else
    compinit
fi


select-word-style bash

HISTSIZE=2500
HISTFILE=$HOME/.cache/zsh-hist
SAVEHIST=$HISTSIZE
HISTDUP=erase


zinit cdreplay -q
zle -N toggle-sudo


setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_save_no_dups
setopt hist_find_no_dups


zstyle ":completion:*" menu select
zstyle ":completion:*" use-cache on
zstyle ":completion:*" matcher-list "m:{a-z}={A-Za-z}"
zstyle ":completion:*" list-colors "${(s.:.)LS_COLORS}"


zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions


bindkey "^f" autosuggest-accept
bindkey "^[s" toggle-sudo

bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

bindkey "^[[3;5~" kill-word
bindkey "^H" backward-kill-word
bindkey "^[[3~" delete-char

bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

bindkey "^Z" undo
bindkey "^Y" redo


alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ip="ip --color=auto"

alias vi="nano" vim="nano" nvim="nano"

alias l="lsd --literal --icon always --color always --group-dirs first --date +%x\ %T"
alias ls="lsd --literal --icon always --color always --group-dirs first --date +%x\ %T"
alias ll="lsd --literal --icon always --color always --group-dirs first --date +%x\ %T -lh"
alias lll="lsd --literal --icon always --color always --group-dirs first --date +%x\ %T -lAh"

alias cd="lastcd"
alias rm="trash -v"
alias ff="fastfetch"
alias ssh="kitten ssh"
alias wlcp="wl-copy"
alias hypr="hyprctl dispatch"
alias ncdu="ncdu --exclude Remote --exclude /proc --exclude /run --exclude /mnt --exclude /home/yabai/Library"
alias hist="history 0 | fzf | tr -d "\n" | wl-copy"

alias proj="$Dotfiles/scripts/project"
alias projadd="$Dotfiles/scripts/projects add"
alias projrem="$Dotfiles/scripts/projects rem"

alias thunar="exec thunar . &"
alias code="code-reuse-or-new"

alias g="git"
alias gs="git status"
alias gst="git status"
alias ga="git add"
alias gaa="git add ."
alias gc="git commit -m"
alias gp="git push"
alias gpo="git push origin"


eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"
eval "$(oh-my-posh init zsh --config $Dotfiles/terminal/ohmyposh.toml)"