#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <interface> [pseudonym]"
    exit 1
fi

INTERFACE="$1"
PSEUDONYM="${2:-$INTERFACE}"

was_connected=true
notification_id=0
disconnection_time=0


function is_internet_accessible() {
    ping -c 1 -W 3 -I "$INTERFACE" "1.1.1.1" &> /dev/null
    return $?
}

while true; do
    sleep 1
    current_time=$(date +%s)
    
    if is_internet_accessible; then
        if [ "$was_connected" = false ]; then
            if (( current_time - disconnection_time < 10 )); then
                notify-send -u "low" "Connection through \"$PSEUDONYM\" is UP" --replace-id="$notification_id"
            else
                notify-send -u "critical" "Connection through \"$PSEUDONYM\" is UP"
            fi
            was_connected=true
        fi
    else
        if [ "$was_connected" = true ]; then
            if ! is_internet_accessible; then
                notification_id=$(notify-send -u "critical" "Connection through \"$PSEUDONYM\" is DOWN" --print-id)
                disconnection_time=$(date +%s)
                was_connected=false
            fi
        fi
    fi
done
