#!/usr/bin/bash

options="Shutdown\nReboot\nWindows\nSuspend"

choice=$(echo -e "$options" | fzf --ansi --highlight-line --margin=0%)

case $choice in
    "Shutdown")
        shutdown now
    ;;
    "Reboot")
        shutdown -r now
    ;;
    "Suspend")
        systemctl suspend
    ;;
    *)
        exit
    ;;
esac
