#!/bin/bash

time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$HOME/Pictures/Screenshots"
file="$((999999999999 - $(date +%s)))--${time}.png"


shotnow() {
	cd ${dir} && grim - | tee "$file" | wl-copy
}

shotwin() {
	w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
	w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
	cd ${dir} && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
}

shotarea() {
	cd ${dir} && grim -g "$(slurp -b 1B1F28CC -w 0)" - | tee "$file" | wl-copy
}

shotscreen() {
	cd ${dir} && grim -g "$(slurp -B 1B1F28CC -w 0 -o)" - | tee "$file" | wl-copy
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

if [[ "$1" == "--now" ]]; then
	shotnow
elif [[ "$1" == "--win" ]]; then
	shotwin
elif [[ "$1" == "--area" ]]; then
	shotarea
elif [[ "$1" == "--screen" ]]; then
	shotscreen
else
	echo -e "Available Options : --now --win --area"
fi

exit 0
