#!/bin/bash

iDIR="$HOME/dotfiles/scripts/assets/icons"

get_volume() {
	volume=$(pamixer --get-volume)
	echo "$volume"
}
inc_volume() {
	pamixer --allow-boost --set-volume $(($(pamixer --get-volume) + 5 - $(pamixer --get-volume) % 5))
	notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(get_volume)" -c adjustments -i "$iDIR/volume.png" "$(get_volume)%"
}
dec_volume() {
	pamixer --allow-boost --set-volume $(($(pamixer --get-volume) - 5 - $(pamixer --get-volume) % 5))
	notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(get_volume)" -c adjustments -i "$iDIR/volume.png" "$(get_volume)%"
}
toggle_mute() {
	if [ "$(pamixer --get-mute)" == "false" ]; then
		pamixer -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(get_volume)" -c adjustments -i "$iDIR/volume-mute.png" "OFF"
	elif [ "$(pamixer --get-mute)" == "true" ]; then
		pamixer -u && notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(get_volume)" -c adjustments -i "$iDIR/volume.png" "ON"
	fi
}


toggle_mic() {
	if [ "$(pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" --get-mute)" == "false" ]; then
		pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" -m && notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" --get-volume)" -c adjustments -i "$iDIR/microphone-off.png" "OFF"
	elif [ "$(pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" --get-mute)" == "true" ]; then
		pamixer -u --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" u && notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" --get-volume)" -c adjustments -i "$iDIR/microphone-on.png" "ON"
	fi
}
inc_mic_volume() {
	pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" -i 5
	notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" --get-volume)" -c adjustments -i "$iDIR/microphone-on.png" "$(pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" --get-volume)%"
}
dec_mic_volume() {
	pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" -d 5
	notify-send -h string:x-canonical-private-synchronous:sys-notify -h int:value:"$(pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" --get-volume)" -c adjustments -i "$iDIR/microphone-on.png" "$(pamixer --source "alsa_input.usb-MUSIC-BOOST_HATOR_Signify_ES336C-00.mono-fallback" --get-volume)%"
}

if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
	get_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
	get_mic_icon
elif [[ "$1" == "--mic-inc" ]]; then
	inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
	dec_mic_volume
else
	get_volume
fi
