#!/bin/bash

if [[ "$1" == "--daemon" ]]; then
    wallpaper=$(find "$Dotfiles/" -type f -name "current.wallpaper.*" -print -quit)

    if [[ -z "$wallpaper" ]]; then
        echo "No current wallpaper found."
        exit 1
    fi

    rwpspread --daemon --palette --backend hyprpaper --locker hyprlock --image "$wallpaper"

else
    rm -f $Dotfiles/current.wallpaper.*

    filename="$1"
    extension="${filename##*.}"

    cp "$filename" "$Dotfiles/current.wallpaper.$extension"

    killall "rwpspread --daemon"
    hyprctl dispatch exec "rwpspread --daemon --palette --backend hyprpaper --locker hyprlock --image \"$Dotfiles/current.wallpaper.$extension\""
fi
