#!/usr/bin/env bash

STATUS_CONNECTED_STR='{"text":"Connected","class":"connected","alt":"connected"}'
STATUS_DISCONNECTED_STR='{"text":"Disconnected","class":"disconnected","alt":"disconnected"}'
STATUS_FILE=~/.cache/wireguard-manager-status

function status_wireguard() {
    nmcli connection show | grep -q "wireguard  wg.vpn"
}

function toggle_wireguard() {
    if status_wireguard; then
        nmcli connection down wg.vpn
    else
        nmcli connection up wg.vpn
    fi
    
    if status_wireguard; then
        echo $STATUS_CONNECTED_STR > $STATUS_FILE
    else
        echo $STATUS_DISCONNECTED_STR > $STATUS_FILE
    fi
}

case $1 in
    -s | --status)
        if status_wireguard; then
            echo $STATUS_CONNECTED_STR
        else
            echo $STATUS_DISCONNECTED_STR
        fi
    ;;
    -t | --toggle)
        toggle_wireguard
    ;;
    -i | --init)
        if [ -f "$STATUS_FILE" ]; then
            status=$(cat $STATUS_FILE)
            if [[ $status == $STATUS_CONNECTED_STR ]]; then
                nmcli connection up wg.vpn
                elif [[ $status == $STATUS_DISCONNECTED_STR ]]; then
                nmcli connection down wg.vpn
            else
                echo "Invalid status found in the file: $status"
                exit 1
            fi
        else
            echo "Status file not found. Creating a new one."
            touch $STATUS_FILE
            echo $STATUS_DISCONNECTED_STR > $STATUS_FILE
        fi
    ;;
    *)
        echo "Invalid option. Usage: $0 [-s|--status] [-t|--toggle] [-i|--init]"
        exit 1
    ;;
esac