#!/bin/bash

layoutStatusFile="/tmp/keyboard-layout-status"

printLayout() {
    echo "{\"text\":\"$(python -u  ~/dotfiles/scripts/keyboard-layout get)\"}"
}

printLayout
while inotifywait -e modify "$layoutStatusFile" &> /dev/null; do
    printLayout
done