#!/bin/bash

layoutStatusFile="/tmp/keyboard-layout-status"

printLayout() {
    echo "{\"text\":\"$(cat $layoutStatusFile)\"}"
}

printLayout
while inotifywait -e modify "$layoutStatusFile" &> /dev/null; do
    printLayout
done
